//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciProgramı
{
    using System;
    using System.Collections.Generic;
    
    public partial class dukkan
    {
        public int Id { get; set; }
        public string dukkanadi { get; set; }
        public string dukkanAdres { get; set; }
        public string webSayfa { get; set; }
        public string telefon { get; set; }
    }
}
